sudo: false

language: node_js
node_js:
  - "6"
  - "4"
  - "0.12"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - export CXX=g++-4.8
  - $CXX --version
